[project]
name = "app"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "altair>=5.5.0",
    "pandas>=2.3.1",
    "streamlit>=1.49.1",
]

[dependency-groups]
dev = [
    "pytest>=8.4.2",
]
